"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'LSUIElement': True,
    },
    'iconfile': 'icon/app_icon.icns',
    'resources': ['icon']
}

setup(
    name="ScreenQRReader",
    version="0.1",
    description="画面内のQRコードを読み取ることが出来ます。",
    autor="KNSN92",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
